css/style.css, index.html
links were added to source code and RWD (also for mobile phones)
=> RWD added and links

index.html
=> index.html: add inf oabout v4.0.16 and v4.6.8

css/style.css, index.html
This change does not include v4.8.0.3 yet.
It is to fix the position of the footer and button 'up'. It does take into consideration the possibility of having uBlock or AddBlock active.
=> fixed footers and button up position

index.html
Updated index.html due to new releases info.
=> Add release v.4.8.0.5

index.html
=> index.html: add information about serial console bugs in legacy

index.html
=> index.html: add note about recommended firmware

index.html
=> index.html: add build pipelines status and move about section at the end

index.html
=> index.html: add hashes and signatures for all tarballs

index.html
=> index.html: replace cloud links with 3mdeb FTP links

_posts/2019-08-10-PC-Engines-Firmware-v4-10-0-0.md, index.html
Signed-off-by: Piotr Kleinschmidt <piotr.kleins@gmail.com>
=> index.html: Update file to release v4.10.0.0

index.html
=> index.html: fix broken links

index.html
=> index.html: fix missing links to legacy releases

_posts/2019-09-10-PC-Engines-Firmware-v4-10-0-1.md, index.html
Signed-off-by: Piotr Kleinschmidt <piotr.kleins@gmail.com>
=> Update to releases v4.10.0.1 and v4.0.28

index.html
=> index.html: announce new signing key

_posts/2019-10-10-PC-Engines-Firmware-v4-10-0-2.md, index.html
Signed-off-by: Piotr Kleinschmidt <piotr.kleins@gmail.com>
=> Releases v4.10.0.2 and 4.0.29

_posts/2019-11-08-PC-Engines-Firmware-v4-10-0-3.md, index.html
Signed-off-by: Piotr Kleinschmidt <piotr.kleinschmidt@3mdeb.com>
=> index.html and blog post for mainline release v4.10.0.3 

_posts/2019-12-09-PC-Engines-Firmware-v4-11-0-1.md, _posts/2019-12-10-PC-Engines-Firmware-v4-11-0-1.md, index.html
Signed-off-by: Piotr Kleinschmidt <piotr.kleinschmidt@3mdeb.com>
=> Release v4.11.0.1

gen-index.py
Signed-off-by: Artur Raglis <artur.raglis@3mdeb.com>
=> gen-index.py: add zip links generation

_posts/2020-02-26-PC-Engines-Firmware-v4-11-0-4.md, _posts/2020-02-29-PC-Engines-Firmware-v4-11-0-4.md, index.html
Signed-off-by: Piotr Kleinschmidt <piotr.kleinschmidt@3mdeb.com>
=> Release mainline v4.11.0.4 and legacy v4.0.30

_posts/2020-07-29-PC-Engines-Firmware-v4-12-0-3.md, index.html
This reverts commit 3c63eae9f22ca3defbc358e215efdff64445646b.
=>  WIP: release of coreboot 4.12.02 mainline and 4.0.32 legacy

_posts/2020-07-29-PC-Engines-Firmware-v4-12-0-4.md, _posts/2020-08-31-PC-Engines-Firmware-v4-12-0-4.md, index.html
TODO: update https://asciinema.org
=> Rel v4.12.0.4

css/style.css
css/style.css: changed back accent color to green
=> Website Redsign - styling changes

_site/css/style.css, css/style.css
Signed-off-by: Malwina <malwina.mika@3mdeb.com>
=> _site/css/style.css: change margin and font at newsletter form

_posts/2021-04-30-PC-Engines-Firmware-v4-13-0-6.md
Information for v4.13.0.6 release
=> Rel v4.13.0.6

README.md
=> README.md: add local preview instructions

index.html
=> index.html: update the subscription form

_posts/2021-07-30-PC-Engines-Firmware-v4-14-0-3.md, _posts/2021-08-13-PC-Engines-Firmware-v4-14-0-3.md, index.html
=> Rel v4.14.0.3

_posts/2021-09-17-PC-Engines-Firmware-v4-14-0-4.md, index.html
=> Rel v4.14.0.4

_posts/2021-10-11-PC-Engines-Firmware-v4-14-0-5.md, _posts/2021-10-19-PC-Engines-Firmware-v4-14-0-5.md, index.html
Missing regression test results and charts.
=> Add v4.14.0.5 release info

_posts/2021-11-05-PC-Engines-Firmware-v4-14-0-6.md, index.html
=> Add v4.14.0.6 release info

_posts/2021-12-03-PC-Engines-Firmware-v4-15-0-1.md, index.html
=> Add v4.15.0.1 release info

_posts/2022-02-16-PC-Engines-Firmware-v4-15-0-3.md, index.html
Signed-off-by: Igor Bagnucki <igor.bagnucki@3mdeb.com>
=> Release v4.15.0.3

_posts/2022-03-28-PC-Engines-Firmware-v4.16.0.2.md, index.html
Signed-off-by: Igor Bagnucki <igor.bagnucki@3mdeb.com>
=> _posts/v4.16.0.2: Add release letter

index.html
=> index.html: bump recommended FW version

_posts/2022-05-26-PC-Engines-Firmware-v4.16.0.4.md, index.html
TODO: Update links to regression test results once testing is completed
=> Add v4.16.0.4 release info

_posts/2022-08-24-PC-Engines_Firmware-v4-17-0-3.md
Signed-off-by: Przemyslaw Sulewski <przemyslaw.sulewski@3mdeb.com>
=> release v4.17.0.3

index.html
Signed-off-by: Przemyslaw Sulewski <przemyslaw.sulewski@3mdeb.com>
=> Rel v4.17.0.3 add index

_posts/2023-01-27-PC-Engines_Firmware-v4-19-0-1.md, _posts/2023-02-02-PC-Engines_Firmware-v4-19-0-1.md, index.html
Signed-off-by: Przemyslaw Sulewski <przemyslaw.sulewski@3mdeb.com>
=> release v4.19.0.1

index.html
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>
=> index.html: add announcement on top of page
